version: "3.9"
services:
  backend:
    build: ../backend/app
    container_name: polly_backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
  
  frontend:
    build: ../frontend
    container_name: polly_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

networks:
  default:
    name: polly_net
